@extends('backend.home')

@section('js')

<!-- Page level plugins -->
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

<!-- Page level custom scripts -->
<script src="{{ asset('js/demo/datatables-demo.js') }}"></script>




<!-- Page level custom scripts -->
<script src="{{ asset('js/jquery.searchabledropdown-1.0.8.min.js') }}"></script>
<script>
	$(document).ready(function() {
		$("select").searchable({
			maxListSize: 20,						// if list size are less than maxListSize, show them all
			maxMultiMatch: 10,						// how many matching entries should be displayed
			exactMatch: true,						// Exact matching on search
			wildcards: false,						// Support for wildcard characters (*, ?)
			ignoreCase: true,						// Ignore case sensitivity
			latency: 200,							// how many millis to wait until starting search
			warnMultiMatch: 'top {0} matches ...',	// string to append to a list of entries cut short by maxMultiMatch 
			warnNoMatch: 'no matches ...',			// string to show in the list when no entries match
			zIndex: 'auto'							// zIndex for elements generated by this plugin
	   	});
	});
	</script>
<script type="text/javascript">
	$('#property_id').change(function(){
		var id = $(this).val();
		if(id > 0)
		{
			$.ajax({
			   type:"get",
			   url:"http://127.0.0.1:8000/property/unit/list/"+id,
			   'type': 'GET',
			   'dataType': 'JSON',
			   success:function(res)
			   {       
					if(res)
					{
						$("#unit_id").empty();
						$.each(res,function(key,value){
							console.log(value);
							$("#unit_id").append('<option value="'+value.id+'">'+value.name+'</option>');
						});
					}
			   }
	
			});
		}
		else
		{
			$("#unit_id").empty();
		}
	});
	</script>

@endsection

@section('content')

<div class="container-fluid">

	<!-- Page Heading -->

	<div class="row">
		<div class="col-md-12">
			<!-- Page Heading -->
			<h3 class="text text-info">Payment Report</h3>
			<a href="{{ route('payment_add_form') }}" class="btn btn-primary marginBottom">Collect New Payment</a>
		</div>
	</div>

	<form method="GET" action="{{ route('payment_filter') }}">
		{{--  @csrf  --}}
		<div class="form-group">
			<label for="tenant_id" class="form-label">Select Tenant <span class="required_field"> (*) </span></label>
			<select id="tenant_id" class="form-control" name="tenant_id">
				<option value="">Select Tenant</option>
				@foreach ( $data['tenants'] as $tenant )
					<option value="{{ $tenant->id }}" <?php if( !empty( $_GET['tenant_id'] ) && $_GET['tenant_id'] == $tenant->id ) { echo 'selected'; } ?>>{{ $tenant->name }}</option>
				@endforeach
			</select>
		</div>

		<div class="form-group">
			<label for="property_id" class="form-label">Select Property <span class="required_field"> (*) </span></label>
			<select id="property_id" class="form-control" name="property_id">
				<option value="">Select Property</option>
				@foreach ( $data['properties'] as $property )
					<option value="{{ $property->id }}" <?php if( !empty( $_GET['property_id'] ) && $_GET['property_id'] == $property->id ) { echo 'selected'; } ?> >{{ $property->name }}</option>
				@endforeach
			</select>
		</div>

		<div class="form-group">
			<label for="unit_id" class="form-label">Select Unit ID <span class="required_field"> (*) </span></label>
			<select id="unit_id" class="form-control" name="unit_id">
				<?php if( !empty( $_GET["property_id"] )  ) {
					?>
					<option value="">Select Property Unit</option>
					@foreach ( $data['propertyUnit'] as $propertyUnit )
						<option value="{{ $propertyUnit->id }}" <?php if( !empty( $_GET['unit_id'] ) && $_GET['unit_id'] == $propertyUnit->id ) { echo 'selected'; } ?>>{{ $propertyUnit->name }}</option>
					@endforeach
				<?php } ?>
			</select>
		</div>

		<div class="form-group">
					<label for="payment_status" class="form-label">Payment Status  <span class="required_field"> (*) </span></label>
					<select id="payment_status" class="form-control" name="payment_status">
						<option value=""> Payment Status</option>
						<option value="1" <?php if( !empty( $_GET['payment_status'] ) && $_GET['payment_status'] == '1' ) { echo 'selected'; } ?> >PENDING</option>
						<option value="2" <?php if( !empty( $_GET['payment_status'] ) && $_GET['payment_status'] == '2' ) { echo 'selected'; } ?>  >RECORDED</option>
						<option value="3" <?php if( !empty( $_GET['payment_status'] ) && $_GET['payment_status'] == '3' ) { echo 'selected'; } ?>  >DEPOSITED</option>
					</select>
				</div>

		<div class="form-group">
			<label for="payment_date"> From  </label>
			<input type="date" name="start_date" class="form-control"  value="<?php if( !empty($_GET['start_date'])) { echo $_GET['start_date']; } ?>"   placeholder="From" >
		</div>

		<div class="form-group">
			<label for="payment_date"> From  </label>
			<input type="date" name="end_date" class="form-control"  value="<?php if( !empty($_GET['end_date'])) { echo $_GET['end_date']; } ?>"  placeholder="To">
		</div>

		<button type="submit" class="btn btn-primary">Search</button>

		</form>



	<div class="row">
		<div class="col-md-12">
			{{--  Property List  Start   --}}
			<!-- DataTales Example -->
			<div class="card shadow mb-4">

				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
							<thead>
								<tr>
									<th>ID</th>
									<th>Tenant Name</th>
									<th>Property Name</th>
									<th>Property Unit</th>
									<th>Payment Amount</th>
									<th>Payment Date</th>
									<th>Status</th>
									<th>Purpose</th>
									<th>Action</th>
								</tr>
							</thead>
							<tfoot>
								<tr>
									<th>ID</th>
									<th>Tenant Name</th>
									<th>Property Name</th>
									<th>Property Unit</th>
									<th>Payment Amount</th>
									<th>Payment Date</th>
									<th>Status</th>
									<th>Purpose</th>
									<th>Action</th>
								</tr>
							</tfoot>
							<tbody>
								@foreach( $data['payments'] as $payment )

								<?php 
								$tenant         = DB::table( 'tenants' )->where( 'id' , $payment->tenant_id )->first();
								$property       = DB::table( 'properties' )->where( 'id' , $payment->property_id  )->first();
								$property_unite = DB::table( 'property_unities' )->where( 'id' , $payment->unit_id  )->first();
								?>
									<tr>
										<td>{{ $payment->id }}</td>
										<td>{{ $tenant->name }}</td>
										<td>
											<?php
												if( $property )
												{
													echo $property->name;
												}
												else
												{
													echo '';
												}
											?>
										</td>
										<td>
											<?php
											if( $property_unite )
											{
												echo $property_unite->name;
											}
											else
											{
												echo '';
											}
										?>
										</td>
										<td> $ {{ $payment->payment_amount }}</td>
										<td>{{ $payment->payment_date }}</td>
										<td>
											<?php
												if( $payment->payment_purpose == 1)
												{
											
													echo 'Rent';
												}
												elseif( $payment->payment_purpose == 2 )
												{
													echo 'Prorated Rent';
												}
												elseif( $payment->payment_purpose == 3 )
												{
													echo 'Security Deposit';

												}
												elseif( $payment->payment_purpose == 4 )
												{
													echo 'Damage';

												}
												elseif( $payment->payment_purpose == 5 )
												{
													echo 'Other';
												}
											?>
										</td>
										<td>
											<?php

												if( $payment->payment_status == 1)
												{
											
													echo 'PENDING';
												}
												elseif( $payment->payment_status == 2 )
												{
													echo 'RECORDED';
												}
												elseif( $payment->payment_status == 3 )
												{
													echo 'DEPOSITED';

												}
											
											?>
										</td>
										<td>
											<a class="btn btn-xs btn-info" href="{{ route('payment_show', $payment->id) }}"><i class="fa fa-eye"></i></a>
                                            <a class="btn btn-xs btn-success" href="{{ route('payment_edit', $payment->id) }}"><i class="fa fa-edit"></i></a>
										</td>
									</tr
								@endforeach

							</tbody>
						</table>
					</div>
				</div>
			</div>

			{{--  Property List  Start   --}}

		</div>
	</div>

</div>

@endsection
